### ISSUE TITLE
rebranding suggestion 

### ISSUE THREAD

**Issue by allaeddineomc** [eminfedar/vaktisalah-gtk-rs#2]
i suggest renaming the app into something more readable and easier to search , i also recommend replacing the icon with one that fits in gnome design guidelines since the app is written in GTK , i will try to make an icon as soon as i can

**Comment by eminfedar** [comment]
Happy to receive a PR for that! :)

**Comment by allaeddineomc** [comment]
i have created a pr for the icon #3 
for the name gnome guidelines suggest easy to pronounce single word names , i think "masjid" "salat" "prayer" can be good names
